### ISSUE TITLE
building tells "bash: nim: command not found"

### ISSUE THREAD

**Issue by AlexLuya** [russpowers/nim-atom#11]
Hell,
     I am using ubuntu 14.04+atom 1.5.4,and have done all in this instructions:https://github.com/russpowers/nim-atom.When "ctrl+shift+B",I got:
````bash
bash: nim: command not found
````
but when clicking bottom right icon "show output in new tab",then copy and paste this:
````bash
cd "/..../NimTest/src" && nim c --hints:off --parallelBuild:1 -r "HelloWorld.nim" 2>&1
````
to terminator (not gnome-terminal) and executed it,file got built and outputed

````bash
Hello world!!!
````
Except nim addon's setting,should I do anything else to fix this problem?

**Comment by russpowers** [comment]
Must be some issue with your path settings.  Go to the nim package settings in atom and set the nim executable path.

**Comment by AlexLuya** [comment]
Already set like this:
![atom nim settings](https://cloud.githubusercontent.com/assets/303353/13942889/57e6c998-f032-11e5-8302-73c1f3844cab.png)

**Comment by AlexLuya** [comment]
After fixed another addon's issue,this issue disappeared.

**Comment by russpowers** [comment]
Glad you figured it out!  Which package was it conflicting with?  It might be nice to have here in case someone else runs into the problem.
